---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
